create table if not exists public.horarios_aulas (
    id bigint generated by default as identity primary key,
    dia_semana text not null,
    horario_inicio time not null,
    horario_fim time not null,
    turma text not null,
    professor text not null,
    disciplina text,
    ambiente text,
    ativo boolean default true,
    created_at timestamp with time zone default now()
);

create index if not exists idx_horarios_aulas_dia_semana
    on public.horarios_aulas (dia_semana);

create index if not exists idx_horarios_aulas_professor
    on public.horarios_aulas (professor);

create index if not exists idx_horarios_aulas_turma
    on public.horarios_aulas (turma);

create index if not exists idx_horarios_aulas_ativo
    on public.horarios_aulas (ativo);

alter table public.horarios_aulas enable row level security;

drop policy if exists "horarios_aulas_select_publico" on public.horarios_aulas;
drop policy if exists "horarios_aulas_insert_admin_coordenacao" on public.horarios_aulas;
drop policy if exists "horarios_aulas_update_admin_coordenacao" on public.horarios_aulas;
drop policy if exists "horarios_aulas_delete_admin_coordenacao" on public.horarios_aulas;

create policy "horarios_aulas_select_publico"
on public.horarios_aulas
for select
to anon, authenticated
using (true);

create policy "horarios_aulas_insert_admin_coordenacao"
on public.horarios_aulas
for insert
to authenticated
with check (
    exists (
        select 1
        from public.admins a
        where lower(a.email) = lower(auth.jwt() ->> 'email')
    )
    or exists (
        select 1
        from public.perfis_acesso p
        where lower(p.email) = lower(auth.jwt() ->> 'email')
          and p.perfil = 'coordenacao'
          and p.ativo = true
    )
);

create policy "horarios_aulas_update_admin_coordenacao"
on public.horarios_aulas
for update
to authenticated
using (
    exists (
        select 1
        from public.admins a
        where lower(a.email) = lower(auth.jwt() ->> 'email')
    )
    or exists (
        select 1
        from public.perfis_acesso p
        where lower(p.email) = lower(auth.jwt() ->> 'email')
          and p.perfil = 'coordenacao'
          and p.ativo = true
    )
)
with check (
    exists (
        select 1
        from public.admins a
        where lower(a.email) = lower(auth.jwt() ->> 'email')
    )
    or exists (
        select 1
        from public.perfis_acesso p
        where lower(p.email) = lower(auth.jwt() ->> 'email')
          and p.perfil = 'coordenacao'
          and p.ativo = true
    )
);

create policy "horarios_aulas_delete_admin_coordenacao"
on public.horarios_aulas
for delete
to authenticated
using (
    exists (
        select 1
        from public.admins a
        where lower(a.email) = lower(auth.jwt() ->> 'email')
    )
    or exists (
        select 1
        from public.perfis_acesso p
        where lower(p.email) = lower(auth.jwt() ->> 'email')
          and p.perfil = 'coordenacao'
          and p.ativo = true
    )
);

create table if not exists public.site_settings (
    chave text primary key,
    valor text,
    atualizado_em timestamp with time zone default now()
);

alter table public.site_settings enable row level security;

drop policy if exists "site_settings_select_publico" on public.site_settings;
drop policy if exists "site_settings_insert_admin_coordenacao" on public.site_settings;
drop policy if exists "site_settings_update_admin_coordenacao" on public.site_settings;

create policy "site_settings_select_publico"
on public.site_settings
for select
to anon, authenticated
using (true);

create policy "site_settings_insert_admin_coordenacao"
on public.site_settings
for insert
to authenticated
with check (
    exists (
        select 1
        from public.admins a
        where lower(a.email) = lower(auth.jwt() ->> 'email')
    )
    or exists (
        select 1
        from public.perfis_acesso p
        where lower(p.email) = lower(auth.jwt() ->> 'email')
          and p.perfil = 'coordenacao'
          and p.ativo = true
    )
);

create policy "site_settings_update_admin_coordenacao"
on public.site_settings
for update
to authenticated
using (
    exists (
        select 1
        from public.admins a
        where lower(a.email) = lower(auth.jwt() ->> 'email')
    )
    or exists (
        select 1
        from public.perfis_acesso p
        where lower(p.email) = lower(auth.jwt() ->> 'email')
          and p.perfil = 'coordenacao'
          and p.ativo = true
    )
)
with check (
    exists (
        select 1
        from public.admins a
        where lower(a.email) = lower(auth.jwt() ->> 'email')
    )
    or exists (
        select 1
        from public.perfis_acesso p
        where lower(p.email) = lower(auth.jwt() ->> 'email')
          and p.perfil = 'coordenacao'
          and p.ativo = true
    )
);

insert into public.site_settings (chave, valor, atualizado_em)
values ('riolando_sem_expediente', 'false', now())
on conflict (chave) do nothing;
